name: youplot
description: "Sports route planner."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.3.0
  collection: ^1.19.1
  dartz: ^0.10.1
  dio: ^5.9.2
  equatable: ^2.0.8
  file_picker: ^3.0.4
  fl_chart: ^1.2.0
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1
  flutter_map: ^8.3.0
  froom: ^6.0.0
  gap: ^3.0.1
  geolocator: ^14.0.1
  get_it: ^9.2.1
  google_fonts: ^8.1.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  pdf: ^3.12.0
  permission_handler: ^12.0.2
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.5
  share_plus: ^13.1.0
  shimmer: ^3.0.0
  styled_widget: ^0.4.1
  sqflite: ^2.4.2+1
  uuid: ^4.5.3
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  froom_generator: ^6.0.0
  mockito: ^5.6.4

flutter:
  uses-material-design: true
