package com.you.plot.core.common.utils

val COUNTRY_LIST = listOf(
    "" to "🌍 All countries",
    "af" to "Afghanistan",
    "al" to "Albania",
    "dz" to "Algeria",
    "ad" to "Andorra",
    "ao" to "Angola",
    "ag" to "Antigua and Barbuda",
    "ar" to "Argentina",
    "am" to "Armenia",
    "au" to "Australia",
    "at" to "Austria",
    "az" to "Azerbaijan",
    "bs" to "Bahamas",
    "bh" to "Bahrain",
    "bd" to "Bangladesh",
    "bb" to "Barbados",
    "by" to "Belarus",
    "be" to "Belgium",
    "bz" to "Belize",
    "bj" to "Benin",
    "bt" to "Bhutan",
    "bo" to "Bolivia",
    "ba" to "Bosnia and Herzegovina",
    "bw" to "Botswana",
    "br" to "Brazil",
    "bn" to "Brunei",
    "bg" to "Bulgaria",
    "bf" to "Burkina Faso",
    "bi" to "Burundi",
    "cv" to "Cabo Verde",
    "kh" to "Cambodia",
    "cm" to "Cameroon",
    "ca" to "Canada",
    "cf" to "Central African Republic",
    "td" to "Chad",
    "cl" to "Chile",
    "cn" to "China",
    "co" to "Colombia",
    "km" to "Comoros",
    "cg" to "Congo",
    "cd" to "Democratic Republic of the Congo",
    "cr" to "Costa Rica",
    "ci" to "Côte d'Ivoire",
    "hr" to "Croatia",
    "cu" to "Cuba",
    "cy" to "Cyprus",
    "cz" to "Czechia",
    "dk" to "Denmark",
    "dj" to "Djibouti",
    "dm" to "Dominica",
    "do" to "Dominican Republic",
    "ec" to "Ecuador",
    "eg" to "Egypt",
    "sv" to "El Salvador",
    "gq" to "Equatorial Guinea",
    "er" to "Eritrea",
    "ee" to "Estonia",
    "sz" to "Eswatini",
    "et" to "Ethiopia",
    "fj" to "Fiji",
    "fi" to "Finland",
    "fr" to "France",
    "ga" to "Gabon",
    "gm" to "Gambia",
    "ge" to "Georgia",
    "de" to "Germany",
    "gh" to "Ghana",
    "gr" to "Greece",
    "gd" to "Grenada",
    "gt" to "Guatemala",
    "gn" to "Guinea",
    "gw" to "Guinea-Bissau",
    "gy" to "Guyana",
    "ht" to "Haiti",
    "hn" to "Honduras",
    "hu" to "Hungary",
    "is" to "Iceland",
    "in" to "India",
    "id" to "Indonesia",
    "ir" to "Iran",
    "iq" to "Iraq",
    "ie" to "Ireland",
    "il" to "Israel",
    "it" to "Italy",
    "jm" to "Jamaica",
    "jp" to "Japan",
    "jo" to "Jordan",
    "kz" to "Kazakhstan",
    "ke" to "Kenya",
    "ki" to "Kiribati",
    "kp" to "North Korea",
    "kr" to "South Korea",
    "kw" to "Kuwait",
    "kg" to "Kyrgyzstan",
    "la" to "Laos",
    "lv" to "Latvia",
    "lb" to "Lebanon",
    "ls" to "Lesotho",
    "lr" to "Liberia",
    "ly" to "Libya",
    "li" to "Liechtenstein",
    "lt" to "Lithuania",
    "lu" to "Luxembourg",
    "mg" to "Madagascar",
    "mw" to "Malawi",
    "my" to "Malaysia",
    "mv" to "Maldives",
    "ml" to "Mali",
    "mt" to "Malta",
    "mh" to "Marshall Islands",
    "mr" to "Mauritania",
    "mu" to "Mauritius",
    "mx" to "Mexico",
    "fm" to "Micronesia",
    "md" to "Moldova",
    "mc" to "Monaco",
    "mn" to "Mongolia",
    "me" to "Montenegro",
    "ma" to "Morocco",
    "mz" to "Mozambique",
    "mm" to "Myanmar",
    "na" to "Namibia",
    "nr" to "Nauru",
    "np" to "Nepal",
    "nl" to "Netherlands",
    "nz" to "New Zealand",
    "ni" to "Nicaragua",
    "ne" to "Niger",
    "ng" to "Nigeria",
    "mk" to "North Macedonia",
    "no" to "Norway",
    "om" to "Oman",
    "pk" to "Pakistan",
    "pw" to "Palau",
    "ps" to "Palestine",
    "pa" to "Panama",
    "pg" to "Papua New Guinea",
    "py" to "Paraguay",
    "pe" to "Peru",
    "ph" to "Philippines",
    "pl" to "Poland",
    "pt" to "Portugal",
    "qa" to "Qatar",
    "ro" to "Romania",
    "ru" to "Russia",
    "rw" to "Rwanda",
    "kn" to "Saint Kitts and Nevis",
    "lc" to "Saint Lucia",
    "vc" to "Saint Vincent and the Grenadines",
    "ws" to "Samoa",
    "sm" to "San Marino",
    "st" to "Sao Tome and Principe",
    "sa" to "Saudi Arabia",
    "sn" to "Senegal",
    "rs" to "Serbia",
    "sc" to "Seychelles",
    "sl" to "Sierra Leone",
    "sg" to "Singapore",
    "sk" to "Slovakia",
    "si" to "Slovenia",
    "sb" to "Solomon Islands",
    "so" to "Somalia",
    "za" to "South Africa",
    "ss" to "South Sudan",
    "es" to "Spain",
    "lk" to "Sri Lanka",
    "sd" to "Sudan",
    "sr" to "Suriname",
    "se" to "Sweden",
    "ch" to "Switzerland",
    "sy" to "Syria",
    "tw" to "Taiwan",
    "tj" to "Tajikistan",
    "tz" to "Tanzania",
    "th" to "Thailand",
    "tl" to "Timor-Leste",
    "tg" to "Togo",
    "to" to "Tonga",
    "tt" to "Trinidad and Tobago",
    "tn" to "Tunisia",
    "tr" to "Turkey",
    "tm" to "Turkmenistan",
    "tv" to "Tuvalu",
    "ug" to "Uganda",
    "ua" to "Ukraine",
    "ae" to "United Arab Emirates",
    "gb" to "United Kingdom",
    "us" to "United States",
    "uy" to "Uruguay",
    "uz" to "Uzbekistan",
    "vu" to "Vanuatu",
    "va" to "Vatican City",
    "ve" to "Venezuela",
    "vn" to "Vietnam",
    "ye" to "Yemen",
    "zm" to "Zambia",
    "zw" to "Zimbabwe",
)